version: "3.7"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/ssl/:/etc/ssl/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 80:80
      - 443:443

  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0' -e production
    container_name: ror
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file: .env
    volumes:
      - .:/app
    external_links:
      - db

  db:
    image: postgres:14
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

  # minio:
  #   image: minio/minio:latest
  #   container_name: nice_try_minio
  #   volumes:
  #     - /home/minio:/files
  #   ports:
  #     - 9000:9000
  #     - 9001:9001
  #   environment:
  #     MINIO_ROOT_USER: ${MINIO_ROOT_USER}
  #     MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
  #   command: server --console-address ":9001" /files

volumes:
  db_data:
